// Registry of every indicator a docs page renders with <StockIndicatorChart>.
// Keys are the slug used in `indicator="..."`; the snapshot generator reads the
// same registry, so a chart added here is captured for offline use.

import type { StockIndicatorChartRegistry } from '@facioquo/indy-charts/vue'

export const CHART_INDICATORS: StockIndicatorChartRegistry = {
  Adl:             { uiid: 'Adl',             title: 'Accumulation Distribution Line', chartType: 'oscillator' },
  Adx:             { uiid: 'Adx',             title: 'Average Directional Index', chartType: 'oscillator' },
  Alligator:       { uiid: 'Alligator',       title: 'Williams Alligator' },
  Alma:            { uiid: 'Alma',            title: 'Arnaud Legoux Moving Average' },
  Aroon:           { uiid: 'AROON UP/DOWN',   title: 'Aroon', chartType: 'oscillator' },
  AroonOsc:        { uiid: 'AROON OSC',       title: 'Aroon Oscillator', chartType: 'oscillator' },
  Atr:             { uiid: 'Atr',             title: 'Average True Range', chartType: 'oscillator' },
  Atrp:            { uiid: 'ATRP',            title: 'Average True Range Percent', chartType: 'oscillator' },
  AtrStop:         { uiid: 'ATR-STOP-HL',     title: 'ATR Trailing Stop (High/Low)' },
  AtrStopClose:    { uiid: 'ATR-STOP-CLOSE',  title: 'ATR Trailing Stop (Close)' },
  Awesome:         { uiid: 'AO',              title: 'Awesome Oscillator', chartType: 'oscillator' },
  Beta:            { uiid: 'Beta',            title: 'Beta', chartType: 'oscillator' },
  BollingerBands:  { uiid: 'BB',              title: 'Bollinger Bands®' },
  BollingerBandsPctB: { uiid: 'BB-PCTB',      title: 'Bollinger Bands® %B', chartType: 'oscillator' },
  Bop:             { uiid: 'Bop',             title: 'Balance of Power', chartType: 'oscillator' },
  Cci:             { uiid: 'Cci',             title: 'Commodity Channel Index', chartType: 'oscillator' },
  ChaikinOsc:      { uiid: 'CHAIKIN',         title: 'Chaikin Oscillator', chartType: 'oscillator' },
  Chandelier:      { uiid: 'CHEXIT-LONG',     title: 'Chandelier Exit (long)' },
  ChandelierShort: { uiid: 'CHEXIT-SHORT',    title: 'Chandelier Exit (short)' },
  Chop:            { uiid: 'Chop',            title: 'Choppiness Index', chartType: 'oscillator' },
  Cmf:             { uiid: 'Cmf',             title: 'Chaikin Money Flow', chartType: 'oscillator' },
  Cmo:             { uiid: 'Cmo',             title: 'Chande Momentum Oscillator', chartType: 'oscillator' },
  ConnorsRsi:      { uiid: 'CRSI',            title: 'ConnorsRSI', chartType: 'oscillator' },
  DcPeriods:       { uiid: 'DCPERIOD',        title: 'Dominant Cycle Periods', chartType: 'oscillator' },
  Dema:            { uiid: 'Dema',            title: 'Double Exponential Moving Average' },
  Doji:            { uiid: 'DOJI',            title: 'Doji' },
  Donchian:        { uiid: 'Donchian',        title: 'Donchian Channels' },
  Dpo:             { uiid: 'Dpo',             title: 'Detrended Price Oscillator', chartType: 'oscillator' },
  Dynamic:         { uiid: 'DYN',             title: 'McGinley Dynamic' },
  ElderRay:        { uiid: 'ELDER-RAY',       title: 'Elder-ray Index', chartType: 'oscillator' },
  Ema:             { uiid: 'Ema',             title: 'Exponential Moving Average' },
  Epma:            { uiid: 'Epma',            title: 'Endpoint Moving Average' },
  Fcb:             { uiid: 'Fcb',             title: 'Fractal Chaos Bands' },
  FisherTransform: { uiid: 'FISHER',          title: 'Ehlers Fisher Transform', chartType: 'oscillator' },
  ForceIndex:      { uiid: 'FORCE',           title: 'Force Index', chartType: 'oscillator' },
  Fractal:         { uiid: 'Fractal',         title: 'Williams Fractal' },
  Gator:           { uiid: 'GATOR',           title: 'Gator Oscillator', chartType: 'oscillator' },
  HeikinAshi:      { uiid: 'HEIKIN-ASHI',     title: 'Heikin-Ashi' },
  HL2:             { uiid: 'HL2',             title: 'Median Price (HL2)' },
  HLC3:            { uiid: 'HLC3',            title: 'Typical Price (HLC3)' },
  Hma:             { uiid: 'Hma',             title: 'Hull Moving Average' },
  HtTrendline:     { uiid: 'HT Trendline',    title: 'Hilbert Transform Instantaneous Trendline' },
  Hurst:           { uiid: 'Hurst',           title: 'Hurst Exponent', chartType: 'oscillator' },
  Ichimoku:        { uiid: 'Ichimoku',        title: 'Ichimoku Cloud' },
  Kama:            { uiid: 'Kama',            title: "Kaufman's Adaptive Moving Average" },
  Keltner:         { uiid: 'Keltner',         title: 'Keltner Channels' },
  Kvo:             { uiid: 'Kvo',             title: 'Klinger Volume Oscillator', chartType: 'oscillator' },
  Linear:          { uiid: 'LINEAR',          title: 'Linear regression' },
  Macd:            { uiid: 'Macd',            title: 'Moving Average Convergence / Divergence', chartType: 'oscillator' },
  MaEnvelopes:     { uiid: 'MA-ENV',          title: 'Moving Average Envelopes' },
  Mama:            { uiid: 'Mama',            title: 'MESA Adaptive Moving Average' },
  Marubozu:        { uiid: 'MARUBOZU',        title: 'Marubozu' },
  Mfi:             { uiid: 'Mfi',             title: 'Money Flow Index', chartType: 'oscillator' },
  Obv:             { uiid: 'Obv',             title: 'On-Balance Volume', chartType: 'oscillator' },
  OC2:             { uiid: 'OC2',             title: 'Open-Close Average (OC2)' },
  OHL3:            { uiid: 'OHL3',            title: 'Open-High-Low Average (OHL3)' },
  OHLC4:           { uiid: 'OHLC4',           title: 'Average Price (OHLC4)' },
  ParabolicSar:    { uiid: 'PSAR',            title: 'Parabolic SAR' },
  PivotPoints:     { uiid: 'PIVOT-POINTS',    title: 'Pivot Points' },
  Pivots:          { uiid: 'PIVOTS',          title: 'Pivots' },
  Pmo:             { uiid: 'Pmo',             title: 'Price Momentum Oscillator', chartType: 'oscillator' },
  Pvo:             { uiid: 'Pvo',             title: 'Percentage Volume Oscillator', chartType: 'oscillator' },
  Roc:             { uiid: 'Roc',             title: 'Rate of Change', chartType: 'oscillator' },
  RocWb:           { uiid: 'RocWb',           title: 'Rate of Change with Bands', chartType: 'oscillator' },
  RollingPivots:   { uiid: 'ROLLING-PIVOTS',  title: 'Rolling Pivot Points' },
  Rsi:             { uiid: 'RSI',             title: 'Relative Strength Index', chartType: 'oscillator' },
  Slope:           { uiid: 'Slope',           title: 'Slope and linear regression', chartType: 'oscillator' },
  Sma:             { uiid: 'SMA',             title: 'Simple Moving Average' },
  SmaMad:          { uiid: 'SMA-MAD',         title: 'SMA Error Analysis (MAD)', chartType: 'oscillator' },
  SmaMape:         { uiid: 'SMA-MAPE',        title: 'SMA Error Analysis (MAPE)', chartType: 'oscillator' },
  SmaMse:          { uiid: 'SMA-MSE',         title: 'SMA Error Analysis (MSE)', chartType: 'oscillator' },
  Smi:             { uiid: 'Smi',             title: 'Stochastic Momentum Index', chartType: 'oscillator' },
  Smma:            { uiid: 'Smma',            title: 'Smoothed Moving Average' },
  StarcBands:      { uiid: 'STARC',           title: 'STARC Bands' },
  Stc:             { uiid: 'Stc',             title: 'Schaff Trend Cycle', chartType: 'oscillator' },
  StdDev:          { uiid: 'STDEV',           title: 'Standard deviation', chartType: 'oscillator' },
  StdDevChannels:  { uiid: 'STDEV-CH',        title: 'Standard Deviation Channels' },
  StdDevZScore:    { uiid: 'STDEV-ZSCORE',    title: 'Standard deviation Z-score', chartType: 'oscillator' },
  Stoch:           { uiid: 'STO',             title: 'Stochastic Oscillator', chartType: 'oscillator' },
  StochRsi:        { uiid: 'StochRsi',        title: 'Stochastic RSI', chartType: 'oscillator' },
  SuperTrend:      { uiid: 'SuperTrend',      title: 'SuperTrend' },
  T3:              { uiid: 'T3',              title: 'Tillson T3 Moving Average' },
  Tema:            { uiid: 'Tema',            title: 'Triple Exponential Moving Average' },
  Tr:              { uiid: 'TR',              title: 'True Range', chartType: 'oscillator' },
  Trix:            { uiid: 'Trix',            title: 'Triple EMA Oscillator (TRIX)', chartType: 'oscillator' },
  Tsi:             { uiid: 'Tsi',             title: 'True Strength Index', chartType: 'oscillator' },
  UlcerIndex:      { uiid: 'ULCER',           title: 'Ulcer Index', chartType: 'oscillator' },
  Ultimate:        { uiid: 'Ultimate',        title: 'Ultimate Oscillator', chartType: 'oscillator' },
  VolatilityStop:  { uiid: 'VOL-STOP',        title: 'Volatility Stop' },
  Vortex:          { uiid: 'Vortex',          title: 'Vortex Indicator', chartType: 'oscillator' },
  Vwap:            { uiid: 'Vwap',            title: 'Volume Weighted Average Price' },
  Vwma:            { uiid: 'Vwma',            title: 'Volume Weighted Moving Average' },
  WilliamsR:       { uiid: 'WilliamsR',       title: 'Williams %R', chartType: 'oscillator' },
  Wma:             { uiid: 'Wma',             title: 'Weighted Moving Average' },
  ZigZag:          { uiid: 'ZIGZAG-HL',       title: 'ZigZag (High/Low)' },
  ZigZagClose:     { uiid: 'ZIGZAG-CL',       title: 'ZigZag (Close)' }
}
